# Generated by Django 5.0.4 on 2024-05-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_productimages_warrant_brand_name_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
