# Generated by Django 5.0.4 on 2024-05-16 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_paying_method_checkout_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 15, 2, 36, 559971, tzinfo=datetime.timezone.utc)),
        ),
    ]
