# Generated by Django 5.0.4 on 2024-05-16 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_estimated_arrival'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paying_method',
            new_name='PayingMethod',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 15, 5, 25, 691936, tzinfo=datetime.timezone.utc)),
        ),
    ]
