# Generated by Django 5.0.4 on 2024-05-17 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_paying_method_payingmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 0, 57, 48, 526763, tzinfo=datetime.timezone.utc)),
        ),
    ]
