import datetime
JJVV=[
        {
            "Miembros":
                        [
                            {
                                'antiguedad': 1024,
                                'fecha_incorporacion': datetime.datetime(2021, 5, 10, 0, 0),
                                'identificacion': 'CV001',
                                'informacion_personal': {
                                    'edad': 73,
                                    'genero': 'Masculino',
                                    'nombre': 'Jasmine Ellis'
                                },
                                'nombre_usuario': 'madams'
                            },
                            {
                                'antiguedad': 378,
                                'fecha_incorporacion': datetime.datetime(2023, 2, 15, 0, 0),
                                'identificacion': 'CV002',
                                'informacion_personal': {
                                    'edad': 78,
                                    'genero': 'No binario',
                                    'nombre': 'Nathan Castro'},
                                'nombre_usuario': 'robinsonmercedes'
                            },
                            {
                                'antiguedad': 557,
                                'fecha_incorporacion': datetime.datetime(2022, 8, 20, 0, 0),
                                'identificacion': 'CV003',
                                'informacion_personal': {
                                    'edad': 39,
                                    'genero': 'Masculino',
                                    'nombre': 'Michael Miranda'},
                                'nombre_usuario': 'nhaley'},
                            {
                                'antiguedad': 1210,
                                'fecha_incorporacion': datetime.datetime(2020, 11, 5, 0, 0),
                                'identificacion': 'CV004',
                                'informacion_personal': {'edad': 49,
                                                    'genero': 'Masculino',
                                                    'nombre': 'Nicole Brown'},
                            'nombre_usuario': 'amandafreeman'},
                            {
                                'antiguedad': 1674,
                                'fecha_incorporacion': datetime.datetime(2019, 7, 30, 0, 0),
                                'identificacion': 'CV005',
                                'informacion_personal': {'edad': 46,
                                                    'genero': 'No binario',
                                                    'nombre': 'Jeremy Munoz'},
                                'nombre_usuario': 'randywalker'},
                            {
                                'antiguedad': 722,
                                'fecha_incorporacion': datetime.datetime(2022, 3, 8, 0, 0),
                                'identificacion': 'CV006',
                                'informacion_personal': {'edad': 70,
                                                    'genero': 'No binario',
                                                    'nombre': 'Amanda Williams'},
                                'nombre_usuario': 'leonjames'}
                ]
            ,
            "direccion":"Calle falsa 123",
            "NumeroTef":12345679,
        },
        {
            "Miembros":
            [{'antiguedad': 1024,
  'fecha_incorporacion': datetime.datetime(2021, 5, 10, 0, 0),
  'identificacion': 'CV001',
  'informacion_personal': {'edad': 50,
                           'genero': 'Femenino',
                           'nombre': 'James Davis'},
  'nombre_usuario': 'brookefields'},
 {'antiguedad': 378,
  'fecha_incorporacion': datetime.datetime(2023, 2, 15, 0, 0),
  'identificacion': 'CV002',
  'informacion_personal': {'edad': 32,
                           'genero': 'No binario',
                           'nombre': 'Juan Lewis'},
  'nombre_usuario': 'brenda62'},
 {'antiguedad': 557,
  'fecha_incorporacion': datetime.datetime(2022, 8, 20, 0, 0),
  'identificacion': 'CV003',
  'informacion_personal': {'edad': 28,
                           'genero': 'No binario',
                           'nombre': 'Brandon Hardin'},
  'nombre_usuario': 'tbennett'},
 {'antiguedad': 1210,
  'fecha_incorporacion': datetime.datetime(2020, 11, 5, 0, 0),
  'identificacion': 'CV004',
  'informacion_personal': {'edad': 36,
                           'genero': 'Masculino',
                           'nombre': 'Brian Henderson'},
  'nombre_usuario': 'gilmorebrandon'},
 {'antiguedad': 1674,
  'fecha_incorporacion': datetime.datetime(2019, 7, 30, 0, 0),
  'identificacion': 'CV005',
  'informacion_personal': {'edad': 24,
                           'genero': 'Masculino',
                           'nombre': 'Terry Vang'},
  'nombre_usuario': 'danielwebb'},
 {'antiguedad': 722,
  'fecha_incorporacion': datetime.datetime(2022, 3, 8, 0, 0),
  'identificacion': 'CV006',
  'informacion_personal': {'edad': 35,
                           'genero': 'No binario',
                           'nombre': 'Jose Smith'},
  'nombre_usuario': 'annamays'}]

                ,
            "direccion":"Calle real 123",
            "NumeroTef":12345679,
        },
        {
            "Miembros":
[{'antiguedad': 1024,
  'fecha_incorporacion': datetime.datetime(2021, 5, 10, 0, 0),
  'identificacion': 'CV001',
  'informacion_personal': {'edad': 27,
                           'genero': 'Femenino',
                           'nombre': 'Teresa Kramer'},
  'nombre_usuario': 'charlenebecker'},
 {'antiguedad': 378,
  'fecha_incorporacion': datetime.datetime(2023, 2, 15, 0, 0),
  'identificacion': 'CV002',
  'informacion_personal': {'edad': 43,
                           'genero': 'No binario',
                           'nombre': 'Juan Pruitt'},
  'nombre_usuario': 'brandoncastillo'},
 {'antiguedad': 557,
  'fecha_incorporacion': datetime.datetime(2022, 8, 20, 0, 0),
  'identificacion': 'CV003',
  'informacion_personal': {'edad': 29,
                           'genero': 'No binario',
                           'nombre': 'Gregory Arnold'},
  'nombre_usuario': 'joshua74'},
 {'antiguedad': 1210,
  'fecha_incorporacion': datetime.datetime(2020, 11, 5, 0, 0),
  'identificacion': 'CV004',
  'informacion_personal': {'edad': 64,
                           'genero': 'No binario',
                           'nombre': 'Jessica Martin'},
  'nombre_usuario': 'kimberlybrown'},
 {'antiguedad': 1674,
  'fecha_incorporacion': datetime.datetime(2019, 7, 30, 0, 0),
  'identificacion': 'CV005',
  'informacion_personal': {'edad': 25,
                           'genero': 'Femenino',
                           'nombre': 'Laurie Park'},
  'nombre_usuario': 'jamesmorris'},
 {'antiguedad': 722,
  'fecha_incorporacion': datetime.datetime(2022, 3, 8, 0, 0),
  'identificacion': 'CV006',
  'informacion_personal': {'edad': 32,
                           'genero': 'No binario',
                           'nombre': 'Brad White'},
  'nombre_usuario': 'austinstokes'}]
                ,
            "direccion":"ubicacion falsa 123",
            "NumeroTef":12345679,
        },
        {
            "Miembros":
            
            [{'antiguedad': 1024,
  'fecha_incorporacion': datetime.datetime(2021, 5, 10, 0, 0),
  'identificacion': 'CV001',
  'informacion_personal': {'edad': 71,
                           'genero': 'Femenino',
                           'nombre': 'David Burgess'},
  'nombre_usuario': 'mary08'},
 {'antiguedad': 378,
  'fecha_incorporacion': datetime.datetime(2023, 2, 15, 0, 0),
  'identificacion': 'CV002',
  'informacion_personal': {'edad': 72,
                           'genero': 'No binario',
                           'nombre': 'Kathleen Benson'},
  'nombre_usuario': 'jenniferalexander'},
 {'antiguedad': 557,
  'fecha_incorporacion': datetime.datetime(2022, 8, 20, 0, 0),
  'identificacion': 'CV003',
  'informacion_personal': {'edad': 74,
                           'genero': 'No binario',
                           'nombre': 'Michelle Harper'},
  'nombre_usuario': 'nandrade'},
 {'antiguedad': 1210,
  'fecha_incorporacion': datetime.datetime(2020, 11, 5, 0, 0),
  'identificacion': 'CV004',
  'informacion_personal': {'edad': 63,
                           'genero': 'No binario',
                           'nombre': 'Chase Rojas'},
  'nombre_usuario': 'ysmith'},
 {'antiguedad': 1674,
  'fecha_incorporacion': datetime.datetime(2019, 7, 30, 0, 0),
  'identificacion': 'CV005',
  'informacion_personal': {'edad': 68,
                           'genero': 'Masculino',
                           'nombre': 'Joe Hardy'},
  'nombre_usuario': 'ereese'},
 {'antiguedad': 722,
  'fecha_incorporacion': datetime.datetime(2022, 3, 8, 0, 0),
  'identificacion': 'CV006',
  'informacion_personal': {'edad': 65,
                           'genero': 'Femenino',
                           'nombre': 'Eric Roberts'},
  'nombre_usuario': 'wcortez'}]
            ,
            "direccion":"Calle inventada 123",
            "NumeroTef":12345679,
        },
        {
            "Miembros":
[{'antiguedad': 1024,
  'fecha_incorporacion': datetime.datetime(2021, 5, 10, 0, 0),
  'identificacion': 'CV001',
  'informacion_personal': {'edad': 54,
                           'genero': 'Femenino',
                           'nombre': 'Evan Mcclain'},
  'nombre_usuario': 'chenelizabeth'},
 {'antiguedad': 378,
  'fecha_incorporacion': datetime.datetime(2023, 2, 15, 0, 0),
  'identificacion': 'CV002',
  'informacion_personal': {'edad': 66,
                           'genero': 'Masculino',
                           'nombre': 'Steven Grant'},
  'nombre_usuario': 'joseph50'},
 {'antiguedad': 557,
  'fecha_incorporacion': datetime.datetime(2022, 8, 20, 0, 0),
  'identificacion': 'CV003',
  'informacion_personal': {'edad': 38,
                           'genero': 'No binario',
                           'nombre': 'Jonathan Flores'},
  'nombre_usuario': 'meyerslori'},
 {'antiguedad': 1210,
  'fecha_incorporacion': datetime.datetime(2020, 11, 5, 0, 0),
  'identificacion': 'CV004',
  'informacion_personal': {'edad': 34,
                           'genero': 'Masculino',
                           'nombre': 'Walter Chapman'},
  'nombre_usuario': 'estradaerin'},
 {'antiguedad': 1674,
  'fecha_incorporacion': datetime.datetime(2019, 7, 30, 0, 0),
  'identificacion': 'CV005',
  'informacion_personal': {'edad': 48,
                           'genero': 'Femenino',
                           'nombre': 'Terry Martin'},
  'nombre_usuario': 'ugarrison'},
 {'antiguedad': 722,
  'fecha_incorporacion': datetime.datetime(2022, 3, 8, 0, 0),
  'identificacion': 'CV006',
  'informacion_personal': {'edad': 72,
                           'genero': 'Masculino',
                           'nombre': 'Sierra Allen'},
  'nombre_usuario': 'ngarza'}]
                ,
            "direccion":"Calle fantasia 123",
            "NumeroTef":12345679,
        }
    ]
for count,i in enumerate(JJVV):
    for j in i["Miembros"]:
        print(f"Usuario {j["nombre_usuario"]} se incorporó a la junta de vecinos N°{count} en {j["fecha_incorporacion"].strftime("%d-%m-%y")}")