# Generated by Django 5.0.4 on 2024-05-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_city_region_user_profile_pic_client_adress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
